var users;
users = [];
var user1;
user1 = { userName: "imran", userId: 520 };
users.push(user1);
var user2;
user2 = { userName: 'likon', userId: 519 };
users.push(user2);
var user3;
user3 = { userName: 'rafid', userId: 518 };
users.push(user3);
console.log(users);
